version: '2'

services:
	nginx:
	    image: nginx:latest
	    volumes:
	        - "/path/to/nginx.conf:/etc/nginx/nginx.conf:ro"
	        - "/path/to/project:/home/docker:ro"

	hhvm:
	    image: hhvm:latest
	    volumes:
	        - "/path/to/project:/home/docker:rw"
	    dns_search:
	        - "hhvm"